### ISSUE TITLE
Find & Replace Text

### ISSUE THREAD

**Issue by Xarcell** [zedapp/zed#89]
New Feature Request:

A find & replace text feature is badly needed.

I don't have any ideas for the UI either, as Zed is unique with it's UI. I don't know how far you could take it either, but a "replace all instances" within a document would be good too, and maybe even "replace all within folder", but I don't see how you could add that last one.

**Comment by Aldekein** [comment]
Oh, it's 2023 and this feature is still not available. 
I'm on a Mac and I browsed through all available Zed menus and I still cannot do find-and-replace 🪦

**Comment by lalomartins** [comment]
> Oh, it's 2023 and this feature is still not available. I'm on a Mac and I browsed through all available Zed menus and I still cannot do find-and-replace 🪦

Are you sure you're in the right repository? This Zed hasn't been developed since 2015, so it's not really surprising it hasn't closed an issue from 2014. If you're looking for the newer editor of the same name, Rust-based and developed more or less by the same team as Atom was originally, that's not here, not Open Source yet, and therefore no public repository. https://zed.dev/

**Comment by Aldekein** [comment]
Oh, now I see! Yes, I tried the Zed.dev app. Thank you for the clarification!

**Comment by lalomartins** [comment]
@zefhemel might make sense to archive this repo to avoid confusion
